components_manager:
    task_processors:
        main-task-processor:
            worker_threads: 4
        fs-task-processor:
            worker_threads: 1

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: 8081
                task_processor: main-task-processor
        logging:
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard

        handler-create-user:
            path: /api/v1/users
            method: POST
            task_processor: main-task-processor

        handler-get-user:
            path: /api/v1/users/{login}
            method: GET
            task_processor: main-task-processor

        handler-search-users:
            path: /api/v1/users/search
            method: GET
            task_processor: main-task-processor

        handler-login:
            path: /api/v1/auth/login
            method: POST
            task_processor: main-task-processor

        testsuite-support:

        default-secdist-provider:
            missing-ok: true
            environment-secrets-key: SECDIST_CONFIG

        secdist:

        redis-delivery:
            groups:
              - config_name: delivery-db
                db: delivery-db
                sharding_strategy: RedisStandalone
            subscribe_groups: []
            thread_pools:
                redis_thread_pool_size: 2
                sentinel_thread_pool_size: 1

        mongo-delivery-db:
            dbconnection#env: MONGO_DSN
            dbconnection#fallback: mongodb://delivery_mongo:delivery_mongo_password@mongodb:27017/delivery_db?authSource=admin

        http-client:
        http-client-core:
        http-client-middleware-pipeline:
        dns-client:

        tests-control:
            method: POST
            path: /tests/control
            task_processor: main-task-processor

        handler-ping:
            method: GET
            path: /ping
            task_processor: main-task-processor