components_manager:
    task_processors:
        main-task-processor:
            worker_threads: 4
        fs-task-processor:
            worker_threads: 1

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: 8082
                task_processor: main-task-processor
        logging:
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard

        jwt-auth-component:
            secret: "jwt-secret-key"

        handler-create-parcel:
            path: /api/v1/parcels
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - jwt-auth

        handler-get-user-parcels:
            path: /api/v1/users/{id}/parcels
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                  - jwt-auth

        testsuite-support:

        postgres-delivery-db:
            dbconnection#env: POSTGRES_DSN
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true
            connlimit_mode: auto

        http-client:
        http-client-core:
        http-client-middleware-pipeline:
        dns-client:

        tests-control:
            method: POST
            path: /tests/control
            task_processor: main-task-processor

        handler-ping:
            method: GET
            path: /ping
            task_processor: main-task-processor