components_manager:
  task_processors:
    main-task-processor:
      worker_threads: 4
    fs-task-processor:
      worker_threads: 1

  default_task_processor: main-task-processor

  components:
    logging:
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: '@stderr'
          level: info
          overflow_behavior: discard

    server:
      listener:
        port: 8080
        task_processor: main-task-processor

    user-storage:

    handler-search-users:
      path: /users
      method: GET
      task_processor: main-task-processor

    handler-create-user:
      path: /users
      method: POST
      task_processor: main-task-processor

    handler-get-user:
      path: /users/{login}
      method: GET
      task_processor: main-task-processor

    parcel-storage:

    handler-create-parcel:
      path: /parcels
      method: POST
      task_processor: main-task-processor

    handler-get-user-parcels:
      path: /users/{user_id}/parcels
      method: GET
      task_processor: main-task-processor

    delivery-storage:

    handler-create-delivery:
      path: /deliveries
      method: POST
      task_processor: main-task-processor

    handler-get-deliveries:
      path: /deliveries
      method: GET
      task_processor: main-task-processor
